import Link from "next/link";
import { Logo } from "../components/Logo";

export default function TermsPage() {
  return (
    <main className="min-h-screen flex justify-center px-4 py-16">
      <div className="max-w-2xl w-full">
        <div className="flex items-center justify-between mb-8">
          <Logo size="sm" />
          <Link href="/" className="text-sm text-muted hover:text-foreground transition-colors">
            &larr; Back
          </Link>
        </div>

        <h1 className="text-2xl font-bold mb-6">Terms of Service</h1>

        <div className="flex flex-col gap-5 text-sm leading-relaxed text-muted">
          <section>
            <h2 className="text-foreground font-medium mb-2">Service Description</h2>
            <p>
              We Hear You is a platform for capturing, analyzing, and classifying qualitative
              feedback from video and transcription sources. By using this service, you agree
              to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-medium mb-2">Acceptable Use</h2>
            <p>
              You agree to use We Hear You only for lawful purposes. You are responsible for
              ensuring you have appropriate consent to collect and process the personal data
              of individuals whose responses are submitted to the platform.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-medium mb-2">Data Ownership</h2>
            <p>
              You retain ownership of all data submitted to We Hear You, including
              transcriptions, analysis results, and configuration settings. We do not claim
              any intellectual property rights over your content.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-medium mb-2">AI-Generated Insights</h2>
            <p>
              Analysis results — including themes, sentiment, mood, and persona classifications
              — are generated by AI and should be treated as suggestions, not definitive
              assessments. We Hear You is not responsible for decisions made based on
              AI-generated insights.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-medium mb-2">Service Availability</h2>
            <p>
              We strive to maintain high availability but do not guarantee uninterrupted
              service. We reserve the right to modify or discontinue features with reasonable
              notice.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-medium mb-2">Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href="mailto:hello@wehearyou.io" className="text-accent hover:underline">
                hello@wehearyou.io
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
